import turtle
boxie = turtle.Pen()
boxie.up()
boxie.forward(10)
boxie.down()
boxie.forward(40)
boxie.up()
boxie.forward(10)
boxie.left(90)
boxie.forward(10)
boxie.down()
boxie.forward(40)
boxie.up()
boxie.forward(10)
boxie.left(90)
boxie.forward(10)
boxie.down()
boxie.forward(40)
boxie.up()
boxie.forward(10)
boxie.left(90)
boxie.forward(10)
boxie.down()
boxie.forward(40)
boxie.up()
boxie.forward(10)
boxie.hideturtle()

